/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dik.ucgende.hipotenus;

import java.util.Scanner;

public class App {
    
    public static void main(String[] args)
    {
        
       double  ArmutKg=2.14,
               ElmaKg=3.67,
               DomatesKg=1.11,
               MuzKg=0.95,
               PatlicanKg=5.00;
               
       
       double  Armut,Elma,Domates,Muz,Patlican,ToplamTutar=0;

       Scanner input = new Scanner(System.in);
       System.out.print("Armut Kaç Kilo ? : ");
       Armut = input.nextDouble();
       
       System.out.print("Elma Kaç Kilo ? : ");
       Elma = input.nextDouble();
       
       System.out.print("Domates Kaç Kilo ? : ");
       Domates = input.nextDouble();
       
       System.out.print("Muz Kaç Kilo ? : ");
       Muz = input.nextDouble();
       
       System.out.print("Patlican Kaç Kilo ? : ");
       Patlican = input.nextDouble();
       
       ToplamTutar=
               (Armut*ArmutKg)+(ElmaKg*Elma)+(Domates*DomatesKg)+(Muz*MuzKg)
                +(Patlican*PatlicanKg);
     
       
       System.out.print("Toplam Tutar : "+ToplamTutar);
       
       
    }
}
