/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hesap.makinesi;

import java.util.Scanner;

public class App {
    public static void main(String[] args) 
    {
        double sonuc=0;
        int a,b,secim;
        Scanner input = new Scanner(System.in);
        System.out.print("Birinci Sayıyı Giriniz: ");
        a= input.nextInt();
        System.out.print("İkinci Sayıyı Giriniz: ");
        b= input.nextInt();
        System.out.print("Girilen Sayılar :"+a+","+b);
        System.out.print("İşlem Seciniz: \n1.Toplama\n2.Cikarma\n3.Carpma\n4Bolme");
        secim= input.nextInt();
        switch(secim)  
        {
            case 1:
                 sonuc=a+b;
                break;
            case 2:
                 sonuc=a-b;
                break;
            case 3:
                 sonuc=a*b;
                break;
            case 4:
                if (b!=0) {
                   sonuc=a/b; 
                }
                else{
                System.out.print("Sayıyı 0'la bölemezsiniz: ");
                }
                System.out.print("Menuden Secim yapınız.");
                break;
            default:  
                
               break; 
        } 
        System.out.print("Sonuc: "+sonuc);
    }
}
