/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package odev.employee;

public class App {
 
    public static void main(String[] args) {

        Employee employee = new Employee("Ali",1500,50,1980);   
        employee.ToString();
        
        Employee employee2 = new Employee("Mehmet",1000,45,2010);
        employee2.ToString();
        
        
        
    }
}
