/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pratik.array.ortalama;

public class App {

    public static void main(String[] args) {
        int[] numbers = {1, 2, 3, 4, 5,6};
        
        double harmonikOrt = 0.0,harmonikSeri=0.0;
       
        for (int i = 0; i < numbers.length; i++) {
             harmonikSeri += 1.0 / numbers[i];
        }
        harmonikOrt = numbers.length/harmonikSeri;
        
        System.out.println("Harmonik Ortalama : " + harmonikOrt);

        
    }
}
