/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hesap.makinesi;

import java.util.Scanner;

public class App {
    public static void main(String[] args) 
    {
        /*
        Sıcaklık 5'dan küçük ise "Kayak" yapmayı öner.
        Sıcaklık 5 ve 15 arasında ise "Sinema" etkinliğini öner.
        Sıcaklık 15 ve 25 arasında ise "Piknik" etkinliğini öner.
        Sıcaklık 25'ten büyük ise "Yüzme" etkinliğini öner.
        */
        int derece;
        Scanner input = new Scanner(System.in);
        System.out.print("derece giriniz: ");
        derece= input.nextInt();
        if (derece < 5) {
             System.out.println("Kayak yapabilirsiniz.");
        }
        else if(derece > 5 && derece<=25)
        {
            if (derece >= 10)
            {
                 System.out.println("Pikniğe gidebilrisiniz.");
            }
            if(derece<=15)
            {
                System.out.println("Sinemaya gidebilrisiniz.");
            }
        }
        else
        {
              System.out.println("Yüzmeye gidebilrisiniz: ");
        }
    }
}
