/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pratik.duplicate;

import java.util.Arrays;

public class App {
    static boolean isFind(int[]arr,int value){
        for (int i : arr) {
            if (i==value) {
                 return true;
            }
        }
        return false;
    }
    public static void main(String[] args) {
      
        int[] list ={3,7,3,3,2,9,10,21,1,33,9,1};     
        int[] duplicateList =new int[list.length];
        int sayac=0;
        for (int i = 0; i < list.length; i++) {
            
            for (int j = 0; j < list.length; j++) {
                if ((i!=j) &&list[i] == list[j]) 
                {
                    if (!isFind(duplicateList,list[j])) {
                        duplicateList[sayac++]=list[i]; break;
                    }
                }
            }
        }
        System.out.print(Arrays.toString(duplicateList));
    }
}
