/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dik.ucgende.hipotenus;

import java.util.Scanner;

public class App {
    
    public static void main(String[] args)
    {
        int r;
        double pi = Math.PI;
        Scanner input = new Scanner(System.in);
        System.out.print("Dairenin yarıçapını giriniz : ");
        r = input.nextInt();
        
        double alani=pi * r * r;
        double cevresi= 2 * pi * r;
        
        System.out.println("Dairenin alanı : "+alani);
        System.out.println("Dairenin cevresi : "+cevresi  );     
    }
}
