/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dik.ucgende.hipotenus;

import java.util.Scanner;

public class App {
    
    public static void main(String[] args)
    {
       double  boy,kilo, sonuc=0;
       Scanner input = new Scanner(System.in);
       System.out.print("Lütfen boyunuzu (metre cinsinde) giriniz : ");
       boy = input.nextDouble();
         
       System.out.print("Lütfen kilonuzu giriniz : ");
       kilo = input.nextInt();
       sonuc=kilo/(boy*boy);
         
       System.out.print("Vücut Kitle İndeksiniz : " + sonuc);
        
        
    }
}
