/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hesap.makinesi;

import java.util.Scanner;

public class App {
    public static void main(String[] args) 
    {
        String userName,password;
        Scanner input = new Scanner(System.in);
        
        System.out.print("username Giriniz: ");
        userName= input.nextLine();
        System.out.print("pasword Giriniz: ");
        password= input.nextLine();
         System.out.println(userName+" "+password);
        if (userName.equals("patika")  && password.equals("java101")) 
        {
            System.out.println("Sisteme Giriş Yaptınız");
        }
        else 
        {
          System.out.println("Giriş Yapılamadı");   
        }
        
    }
}
