/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dik.ucgende.hipotenus;

import java.util.Scanner;

public class App {
    
    public static void main(String[] args) {
      int km;
      double perKm = 2.20, total = 0,startPrice = 10,minPrice=20;
      Scanner input = new Scanner(System.in);
      System.out.print("Mesafe Giriniz(KM cininden) : ");
      km = input.nextInt();
      total=perKm*km;
      total+=startPrice;
      if (total<minPrice)
      {
          total=20;
      }
      System.out.print("Toplam tutar : "+total);
                
    }
}
